project_id = "young-and-hungry-app"

[api]
port = 55421
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55422
shadow_port = 55420
major_version = 15

[studio]
port = 55423
api_url = "http://127.0.0.1"

[analytics]
enabled = false
